export const MemberAccountColumnOptions = [
  { key: "MemberId", label: "Member ID" },
  { key: "Name", label: "Member Name" },
  { key: "BirthOnBS", label: "BirthOnBS" },
  { key: "PermanentAddess", label: "Permanent Addess" },
  { key: "TemporaryAddress", label: "Temporary Address" },
  { key: "ContactNo", label: "Contact No" },
  { key: "CitizenshipNo", label: "Citizenship No" },
  { key: "Father", label: "Father Name" },
  { key: "Mother", label: "Mother Name" },
  { key: "Spouse", label: "Spouse Name" },
  { key: "SavingAccountType", label: "Saving Account" },
  { key: "AccountNo", label: "Account No" },
  { key: "AccountOpenOn", label: "Account OpenOn" },
  { key: "RegisteredOn", label: "Registered On" },
  { key: "MatureDate", label: "Mature Date" },
  { key: "InterestTransferType", label: "Interest Transfer Type" },
  { key: "InterestRate", label: "Interest Rate" },
  { key: "TaxRate", label: "Tax Rate" },
  { key: "InterestTransferAccount", label: "Interest Transfer Acc" },
  { key: "FreezeAmount", label: "Freeze Amount" },
  { key: "GuaranteeAmount", label: "Guarantee Amount" },
  { key: "TermDepositInstallmentAmount", label: "Installment Amount" },
  { key: "InstallmentType", label: "Installment Type" },
  { key: "DueCount", label: "Due Count" },
  { key: "Deposit", label: "Deposit" },
  { key: "Withdraw", label: "Withdraw" },
  { key: "Balance", label: "Balance" },
] as const;

export type ColumnKey = (typeof MemberAccountColumnOptions)[number]["key"];
