export const COLUMN_OPTIONS = [
  { key: "MemberId", label: "Member ID" },
  { key: "FullName", label: "Full Name" },
  { key: "FirstName", label: "First Name" },
  { key: "MiddleName", label: "Middle Name" },
  { key: "LastName", label: "Last Name" },
  { key: "MemberType", label: "Member Type" },
  { key: "BirthOnBS", label: "DOB (BS)" },
  { key: "PermanentAddress", label: "Perm. Address" },
  { key: "TemporaryAddress", label: "Temp. Address" },
  { key: "PhoneNo", label: "Phone" },
  { key: "MobileNo", label: "Mobile" },
  { key: "EmailAddress", label: "Email" },
  { key: "Nationality", label: "Nationality" },
  { key: "CitizenshipNo", label: "Citizenship No" },
  { key: "PassportNo", label: "Passport No" },
  { key: "Occupation", label: "Occupation" },
  { key: "Religion", label: "Religion" },
  { key: "MaritalStatus", label: "Marital Status" },
  { key: "GrandFatherMotherName", label: "Grandfather/Mother" },
  { key: "FatherName", label: "Father" },
  { key: "MotherName", label: "Mother" },
  { key: "SpouseName", label: "Spouse" },
  { key: "Caste", label: "Caste" },
  { key: "Gender", label: "Gender" },
  { key: "Vdc", label: "VDC" },
  { key: "RegistrationOnBS", label: "Reg. Date (BS)" },
  { key: "Status", label: "Status" },
  { key: "MemberGroup", label: "Member Group" },
  { key: "CitizenShipIssuedOnBs", label: "Cit. Issued On (BS)" },
  { key: "CitizenShipIssuedDistrict", label: "Cit. Issued District" },
  { key: "ElectricityNo", label: "Electricity No" },
  { key: "WaterSupplyNo", label: "Water Supply No" },
  { key: "Education", label: "Education" },
  { key: "IncomeRange", label: "Income Range" },
  { key: "StateVDC", label: "State VDC" },
  { key: "MemberYearlyPaymentTillDateOnBs", label: "Yearly Paymt Till (BS)" },
  { key: "NameInNepali", label: "Name (Nepali)" },
  { key: "AddressInNepali", label: "Address (Nepali)" },
] as const;

export type ColumnKey = (typeof COLUMN_OPTIONS)[number]["key"];
